//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 印表機
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 印表機()
        {
            this.異動記錄 = new HashSet<異動記錄>();
        }
    
        public int ID { get; set; }
        public string 使用單位 { get; set; }
        public string 廠牌 { get; set; }
        public string 型號 { get; set; }
        public string 類別 { get; set; }
        public string 購買廠商 { get; set; }
        public Nullable<decimal> 價格 { get; set; }
        public Nullable<System.DateTime> 購買日期 { get; set; }
        public string IP位址 { get; set; }
        public string 碳粉匣_黑 { get; set; }
        public string 碳粉匣_青 { get; set; }
        public string 碳粉匣_紅 { get; set; }
        public string 碳粉匣_黃 { get; set; }
        public string 備註 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<異動記錄> 異動記錄 { get; set; }
    }
}
